cameras:
  camera_default:
    robot_location: "unspecified"
    serial_number: "unspecified"
    streams:
      depth:
        resolution:
          width: 848
          height: 480
        enabled: 1
        fps: 30
        format: z16
      color:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: bgr8
      ir:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: y8
      imu:
        gyro:
          enabled: 0
          fps: 200
        accelerometer:
          enabled: 0
          fps: 200
  camera_0:
    robot_location: A
    serial_number: ""
    streams:
      depth:
        resolution:
          width: 848
          height: 480
        enabled: 1
        fps: 30
        format: z16
      color:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: bgr8
      ir:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: y8
      imu:
        gyro:
          enabled: 0
          fps: 200
        accelerometer:
          enabled: 0
          fps: 200
  camera_1:
    robot_location: B
    serial_number: ""
    streams:
      depth:
        resolution:
          width: 848
          height: 480
        enabled: 1
        fps: 30
        format: z16
      color:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: bgr8
      ir:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: y8
      imu:
        gyro:
          enabled: 0
          fps: 200
        accelerometer:
          enabled: 0
          fps: 200
  camera_2:
    robot_location: C
    serial_number: ""
    streams:
      depth:
        resolution:
          width: 848
          height: 480
        enabled: 1
        fps: 30
        format: z16
      color:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: bgr8
      ir:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: y8
      imu:
        gyro:
          enabled: 0
          fps: 200
        accelerometer:
          enabled: 0
          fps: 200
  camera_3:
    robot_location: D
    serial_number: ""
    streams:
      depth:
        resolution:
          width: 848
          height: 480
        enabled: 1
        fps: 30
        format: z16
      color:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: bgr8
      ir:
        resolution:
          width: 848
          height: 480
        enabled: 0
        fps: 30
        format: y8
      imu:
        gyro:
          enabled: 0
          fps: 200
        accelerometer:
          enabled: 0
          fps: 200